apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config: |
      upstream api {
        server api:8080;
      }
      server {
          listen       80;
          server_name  localhost;
          location / {
            proxy_pass http://api
        }
      }
